name: admob_unit_ids
description: This is a library that provides a common structure for managing AdMob unit IDs licensed under BSD 3-Clause.
version: 1.0.3
homepage: https://github.com/myConsciousness/admob-unit-ids

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  universal_io: ^2.0.4

dev_dependencies:
  test: ^1.16.8
